#############################################################################
##
## Copyright (c) 2008 Captive Metrics Software Corporation.
##                    All rights reserved.
##
## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE-GPL.txt contained within the
## same package as this file. This software is subject to a
## dual-licensing mechanism, the details of which are outlined in
## file LICENSE-DUAL.txt, also contained within this package. Be sure
## to use the correct license for your needs. To view the commercial
## license, read LICENSE-COMMERCIAL.txt also contained within this
## package.
##
## If you do not have access to these files or are unsure which license
## is appropriate for your use, please contact the sales department at
## sales@captivemetrics.com.
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
#############################################################################

language=java
type=jar_file
target=CM.jar
target_dirs="D com/capmet/metrics com/capmet/metrics/jmdr
               com/capmet/metrics/rmi com/capmet/metrics/cm"
extra_obj="com/capmet/metrics/jmdr/MessagesBundle.properties
           com/capmet/metrics/jmdr/MessagesBundle_en_US.properties
           com/capmet/metrics/jmdr/MessagesBundle_en_GB.properties
           com/capmet/metrics/rmi/MessagesBundle.properties
           com/capmet/metrics/rmi/MessagesBundle_en_GB.properties
           com/capmet/metrics/rmi/MessagesBundle_en_US.properties
           com/capmet/metrics/cm/MessagesBundle.properties
           com/capmet/metrics/cm/MessagesBundle_en_GB.properties
           com/capmet/metrics/cm/MessagesBundle_en_US.properties"

#
# post_snap: Makefile exists; doctor it or append it
#
post_snap() {
  makefile=$1
  (
    top=../../..
    $ECHO \\ninstall:\\t$target
    $ECHO \\tcp $target $top/jars
  ) >> $makefile
}
