#############################################################################
##
## Copyright (c) 2006-2007 Captive Metrics Software Corporation.
##                    All rights reserved.
##
## This file is part of the Captive Metrics library of Captivity.
##
## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE-GPL.txt contained within the
## same package as this file. This software is subject to a
## dual-licensing mechanism, the details of which are outlined in
## file LICENSE-DUAL.txt, also contained within this package. Be sure
## to use the correct license for your needs. To view the commercial
## license, read LICENSE-COMMERCIAL.txt also contained within this
## package.
##
## If you do not have access to these files or are unsure which license
## is appropriate for your use, please contact the sales department at
## sales@captivemetrics.com.
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
#############################################################################

JFILES  = CmCpuStat.java CmIoStat.java CmIoMetrics.java \
          CmExceptionParser.java CmMounts.java CmNames.java \
          CmNicStat.java CmNicMetrics.java \
          CmMpStat.java CmMpMetrics.java \
          CmSysInfo.java CmMessages.java CmInstanceSet.java \
          CmProcessMetrics.java CmProcesses.java CmGlobal.java \
          CmSysStat.java CmPageFiles.java CmPFMetrics.java \
          CmCaches.java CmCacheMetrics.java Sort.java CmTcpStat.java
BCFILES = CmCpuStat.class CmIoStat.class CmIoMetrics.class \
          CmExceptionParser.class CmMounts.class CmNames.class \
          CmNicStat.class CmNicMetrics.class \
          CmMpStat.class CmMpMetrics.class \
          CmSysInfo.class CmMessages.class CmInstanceSet.class \
          CmProcessMetrics.class CmProcesses.class CmGlobal.class \
          CmSysStat.class CmPageFiles.class CmPFMetrics.class \
          CmCaches.class CmCacheMetrics.class Sort.class CmTcpStat.class
TOP     = ../../../..
OPTIM   = -g
.SUFFIXES: .java .class

.java.class:
	CLASSPATH=$(TOP):$(JF) javac $(OPTIM) $*.java

default:	$(BCFILES)

all:
	CLASSPATH=$(TOP):$$CLASSPATH javac $(OPTIM) $(JFILES)

clean:
	/bin/rm -fr *.class
