#!/bin/bash

exit_status=0

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script domain/detail read.sh

domainconf=`get_data "$getdomain"`
get_domain "$domainconf"

if [  "$typ" = "" ]; then
    exit 0;
fi

. exec/system/shell/domain/share/disable_$typ

exit $exitstatus
