#!/bin/bash

inc=
out=""

while true
do
    case $1 in
        -I*) inc="$inc $1";;
	 -o) out=$2; shift;;
	  *) break;
    esac
    shift
done

echo > $out
anzahl_args=0
for dir in $*
do
    file=$dir/options.dat
    if [ -f $file ]; then
	for arg in `sed -e "/^\/\//d" -e "/^[ 	]*$/d" < $file | cut -d'"' -f2`
	do
	    i=0
	    error_found=0
	    while [ $i -lt $anzahl_args ]
	    do
		if [ ${args[$i]} = $arg ]; then
		    echo "$file - $arg ist schon definiert " 1>&2
		    echo "    in ${files[$i]}" 1>&2
		    error_found=1
		    break
		fi
	        let i=i+1
	    done

	    args[anzahl_args]=$arg
	    files[anzahl_args]=$file
            
	    let anzahl_args=anzahl_args+1
	done
	cat $file >> $out
    fi
done

exit 0
