#!/bin/bash

exit_status=0

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script domain/detail read.sh
find_script user/data read.sh

user=$vapar2
olduser=$valoginnameInput_old
password=$(dd if=/dev/urandom bs=2048 count=1 2>/dev/null |tr -dc "a-zA-Z0-9"|fold -w 64 |head -1)

if [ ! "$user" = "" ]; then
    . exec/system/shell/domain/user/update
    userdata=`get_data "$getuserdata" "$user"`
    get_userdata "$userdata"
fi

if [ ! "$user" = "$olduser" ]; then

    if [ "$user" = "" ]; then
         . exec/system/shell/domain/user/del 
    elif [ "$olduser" = "" ]; then
         . exec/system/shell/domain/user/add 
    else
         . exec/system/shell/domain/user/move 
    fi
else
    domainconf=`get_data "$getdomain"`
    get_domain "$domainconf"
    
    if [ ! "$typ" = "" ]; then
        . exec/system/shell/domain/user/validuser
        . exec/system/shell/domain/restart/$typ
    fi
fi

exit $exitstatus