#!/bin/bash

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

find_script domain/detail read.sh

domainconf=`get_data "$getdomain"`
get_domain "$domainconf"

if [ ! "$typ" = "" ]; then
  . exec/system/shell/domain/user/setpasswd_$typ
fi
