#!/bin/bash

. exec/system/config/allg.sh
. exec/system/shell/allg/file.sh

. exec/system/shell/allg/db.sh

port=`awk '/^[ \t]*#/ { next } tolower($1) ~ /listen/ { print $2; exit; }' $apache2rootdir/ports.conf`
sport=`awk 'BEGIN { ok=0 } /^[ \t]*#/ { next } /ssl_mod/ { ok=1; next } /mod_gnutls/ { ok=1; next } tolower($1) ~ /listen/ { if ( ok ) { print $2; exit; } }' $apache2rootdir/ports.conf`
	
	
INSERT="SELECT mne_system.apache_add($port, $sport);"
result=`get_data "$INSERT"`;