#############################################################################
##
## Copyright (c) 2006-2007 Captive Metrics Software Corporation.
##                    All rights reserved.
##
## This file is part of the Captive Metrics library of Captivity.
##
## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE-GPL.txt contained within the
## same package as this file. This software is subject to a
## dual-licensing mechanism, the details of which are outlined in
## file LICENSE-DUAL.txt, also contained within this package. Be sure
## to use the correct license for your needs. To view the commercial
## license, read LICENSE-COMMERCIAL.txt also contained within this
## package.
##
## If you do not have access to these files or are unsure which license
## is appropriate for your use, please contact the sales department at
## sales@captivemetrics.com.
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
#############################################################################

JFILES  = PerformanceCategoryInfo.java \
          PerformanceCategory.java PerformanceException.java \
          PerformanceFieldInfo.java PerformanceField.java \
          PerformanceHost.java RMIAccessPoint.java \
          RMIMethods.java \
          PerformanceCollection.java CounterCollection.java \
          CollectionItem.java CategoryClone.java FieldClone.java \
          FieldCollectionPair.java FieldArray.java RemoteJanitor.java \
          CategorySource.java FieldSource.java \
          MDRCategory.java MDRField.java RMIMessages.java \
          CaptiveCollectorStats.java CaptiveConnection.java \
          RMIProperties.java
BCFILES = PerformanceCategoryInfo.class \
          PerformanceCategory.class PerformanceException.class \
          PerformanceFieldInfo.class PerformanceField.class \
          PerformanceHost.class RMIAccessPoint.class \
          RMIMethods.class \
          PerformanceCollection.class CounterCollection.class \
          CollectionItem.class CategoryClone.class FieldClone.class \
          FieldCollectionPair.class FieldArray.class RemoteJanitor.class \
          CategorySource.class FieldSource.class \
          MDRCategory.class MDRField.class RMIMessages.class \
          CaptiveCollectorStats.class CaptiveConnection.class \
          RMIProperties.class
TOP     = ../../../..
OPTIM   = -g
.SUFFIXES: .java .class

.java.class:
	CLASSPATH=$(TOP):$(JF) javac $(OPTIM) $*.java

default:	$(BCFILES)

all:
	CLASSPATH=$(TOP) javac $(OPTIM) $(JFILES)

clean:
	/bin/rm -fr *.class
