#############################################################################
##
## Copyright (c) 2008 Captive Metrics Software Corporation.
##                    All rights reserved.
##
## This file may be used under the terms of the GNU General Public
## License version 2.0 as published by the Free Software Foundation
## and appearing in the file LICENSE-GPL.txt contained within the
## same package as this file. This software is subject to a
## dual-licensing mechanism, the details of which are outlined in
## file LICENSE-DUAL.txt, also contained within this package. Be sure
## to use the correct license for your needs. To view the commercial
## license, read LICENSE-COMMERCIAL.txt also contained within this
## package.
##
## If you do not have access to these files or are unsure which license
## is appropriate for your use, please contact the sales department at
## sales@captivemetrics.com.
##
## This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
## WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
##
#############################################################################

target=XE.jar
language=java
type=jar_file
target_dirs="com/capmet/tools/XE
             com/capmet/tools/XE/rules
             com/capmet/tools/XE/programs"
jars="../../../jars"
classpath=".:../CM:$jars/forms.jar:$jars/looks.jar:$jars/Chart2D.jar"
extra_obj="com/capmet/tools/XE/MessagesBundle_en_GB.properties
           com/capmet/tools/XE/MessagesBundle.properties
           com/capmet/tools/XE/rules/MessagesBundle.properties
           com/capmet/tools/XE/rules/MessagesBundle_en_GB.properties
           com/capmet/tools/XE/rules/MessagesBundle_en_US.properties
           com/capmet/tools/XE/MessagesBundle_en_US.properties
           com/capmet/tools/XE/images/*"

#
# post_snap: Makefile exists; doctor it or append it
#
post_snap() {
  makefile=$1

  (
    top=../../..
    $ECHO \\ninstall:\\t$target
    $ECHO \\tcp $target $top/jars
  ) >> $makefile
}
